openapi: 3.0.0
info:
  title: Feedback App API
  version: 1.0.0
  description: API for managing activities, feedbacks, and user authentication in the Feedback App.

servers:
  - url: http://localhost:3001
    description: Local server

paths:
  /login:
    post:
      summary: User login
      description: Verifies the user's email and password and returns their role.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                pass:
                  type: string
                  example: 123
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Login successful!"
                  role:
                    type: string
                    example: "professor"
        '401':
          description: Authentication error
        '500':
          description: Server error

  /saveActivity:
    post:
      summary: Create a new activity
      description: Saves a new activity to the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                activity:
                  type: string
                  example: "Math Quiz"
                date:
                  type: string
                  format: date
                  example: "2024-12-01"
                accessCode:
                  type: integer
                  example: 1111
                time:
                  type: integer
                  example: 300
      responses:
        '201':
          description: Activity created successfully
        '500':
          description: Server error

  /getActivity:
    post:
      summary: Get activity details
      description: Returns the details of an activity based on the access code.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accessCode:
                  type: integer
                  example: 1111
      responses:
        '200':
          description: Activity found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  activity:
                    type: object
                    properties:
                      activity:
                        type: string
                        example: "Math Quiz"
                      date:
                        type: string
                        format: date
                        example: "2024-12-01"
                      time:
                        type: integer
                        example: 300
        '404':
          description: Activity not found
        '500':
          description: Server error

  /sendFeedback:
    post:
      summary: Send feedback
      description: Submits feedback from a student for an activity.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: integer
                  example: 1111
                reaction:
                  type: string
                  example: "happy"
      responses:
        '201':
          description: Feedback saved successfully
        '500':
          description: Server error

  /getAllFeedback:
    get:
      summary: Get all feedback
      description: Retrieves all feedback submitted by students.
      responses:
        '200':
          description: Feedback retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  feedback:
                    type: array
                    items:
                      type: object
                      properties:
                        activity_code:
                          type: integer
                          example: 1111
                        reaction:
                          type: string
                          example: "happy"
                        created_at:
                          type: string
                          format: date-time
                          example: "2024-12-04T10:00:00Z"
        '500':
          description: Server error
