openapi: 3.0.0
info:
  title: Login API
  version: 1.0.0
  description: API for user authentication.

servers:
  - url: http://localhost:3001
    description: Local server

paths:
  /login:
    post:
      summary: User Login
      description: Authenticates a user and returns their role.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                pass:
                  type: string
                  example: 123
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Login successful!"
                  role:
                    type: string
                    example: "professor"
        '401':
          description: Invalid email or password
        '500':
          description: Server error
