openapi: 3.0.0
info:
  title: Save Activity API
  version: 1.0.0
  description: API to create a new activity.

servers:
  - url: http://localhost:3001
    description: Local server

paths:
  /saveActivity:
    post:
      summary: Create New Activity
      description: Saves an activity in the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                activity:
                  type: string
                  example: "Math Quiz"
                date:
                  type: string
                  format: date
                  example: "2024-12-01"
                accessCode:
                  type: integer
                  example: 1234
                time:
                  type: integer
                  example: 3600
      responses:
        '201':
          description: Activity created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Activity saved successfully!"
        '500':
          description: Server error
